  version: '3'
  dotenv: ['.env']
  tasks:
    test:
      cmds:
        - ./gradlew test
    run:
      cmds:
        - ./gradlew bootRun
    build-image:
      cmds:
        - ./gradlew clean bootJar
        - ./gradlew bootBuildImage --imageName=nmuianga/catalog-service:latest

    #Compiles the code and packages it
    build-app:
      cmds:
        - ./gradlew clean bootJar

    # Build and test the app
    build:
      cmds:
        - ./gradlew build

    create-db:
      cmds:
        - docker run -d --name polar-postgres --network catalog-network -e POSTGRES_USER=${POSTGRES_USER} -e POSTGRES_PASSWORD=${POSTGRES_PASSWORD} -e POSTGRES_DB=${POSTGRES_DB} -p 5432:5432 postgres:14.4